micronaut:
  application:
    name: evident-db-test
endpoints:
  all:
    port: 8085
  health:
    enabled: true
  metrics:
    enabled: true
evidentdb:
  transactor:
    state.dir: ./data/transactor
  service:
    state.dir: ./data/service
kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default:
      linger.ms: 5
  consumers:
    default:
      key:
        deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value:
        deserializer: com.evidentdb.kafka.EventEnvelopeSerde$EventEnvelopeDeserializer
  streams:
    producer.linger.ms: 0
  topics:
    internal-commands:
      name: evidentdb-internal-commands
      partitions: 4
      replication: 3
      min.insync.replicas: 2
#      compression.type: snappy
      retention.ms: -1
    internal-events:
      name: evidentdb-internal-events
      partitions: 4
      replication: 3
      min.insync.replicas: 2
#      compression.type: snappy
      retention.ms: -1
