micronaut:
  application:
    name: evident-db
evidentdb:
  transactor:
    state.dir: ./data/transactor
  service:
    state.dir: ./data/service
kafka:
  bootstrap:
    servers: localhost:9092
  topics:
    internal-commands:
      name: evidentdb-internal-commands
      partitions: 12
      replication: 3
      min.insync.replicas: 2
      compression.type: snappy
      retention.ms: -1
    internal-events:
      name: evidentdb-internal-events
      partitions: 12
      replication: 3
      min.insync.replicas: 2
      compression.type: snappy
      retention.ms: -1
