micronaut:
  application:
    name: evident-db-test
endpoints:
  all:
    port: 8085
  health:
    enabled: true
  metrics:
    enabled: true
evidentdb:
  transactor:
    state.dir: ./data/transactor
  service:
    state.dir: ./data/service
kafka:
  bootstrap:
    servers: localhost:9092
  topics:
    log:
      name: evidentdb-log
      partitions: 12
      replication: 3
      min.insync.replicas: 2
#      compression.type: snappy
      retention.ms: -1
