micronaut:
  application:
    name: evidentdb-${evidentdb.tenant}
evidentdb:
  topics:
    internal-events:
      name: evidentdb-${evidentdb.tenant}-internal-events
    internal-commands:
      name: evidentdb-${evidentdb.tenant}-internal-commands
endpoints:
  all:
    port: 8085
  health:
    enabled: true
  metrics:
    enabled: true
kafka:
  producers:
    service:
      linger.ms: 5
  streams:
    transactor:
      producer.linger.ms: 0
      state.dir: ./data/transactor
